### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by michele-brambilla** [ess-dmsc/conan-hdf5#1] opened 2018-01-31 15:24 UTC
build fails with message

```
ERROR: hdf5/1.10.1-dm1@ess-dmsc/stable: Error in source() method, line 21
	"hdf5-1.10.1.tar.gz"
	ConanException: Error downloading file https://www.hdfgroup.org/package/gzip/?wpdmdl=4301: 'HTTPSConnectionPool(host='www.hdfgroup.org', port=443): Max retries exceeded with url: /package/gzip/?wpdmdl=4301 (Caused by SSLError(CertificateError("hostname 'www.hdfgroup.org' doesn't match either of '2020multnomah.com', '5662979341156352-fe1.pantheonsite.io', 'bearhugit.com', 'blog.g2crowd.com', 'club.destinationsshow.com', 'coachcanada.com', 'dcad.edu', 'dev.changemakers.com', 'dev.pgv.jetphilly.com', 'dev.pophistory.jetphilly.com', 'dev.psfc.jetphilly.com', 'dev.yourrecipeforhappiness.com', 'donatelifepa.com', 'edentek.co.il', 'elevateminnesota.com', 'manchester.destinationsshow.com', 'propermeasure.com', 'ridgemoore-community.com', 'rrha.com', 'schillerway.com', 'sidebarprep.com', 'test.maggyhawk.com', 'thedata.school', 'v2.plainhealth.com', 'www-test.nysenate.gov', 'www.2020multnomah.com', 'www.bearhugit.com', 'www.canaltalodge.com', 'www.club.destinationsshow.com', 'www.coachcanada.com', 'www.dcad.edu', 'www.donatelifepa.com', 'www.manchester.destinationsshow.com', 'www.propermeasure.com', 'www.rrha.com', 'www.schillerway.com', 'www.sidebarprep.com'",),))'
```

**Comment by matthew-d-jones** [comment] 2019-04-24 08:38
Closing issue as error report is for an old version and I am unable to reproduce with current recipe for hdf5/1.10.2-dm2@ess-dmsc/stable

**Closed as completed by matthew-d-jones** 2019-04-24 08:38 UTC
Labels: bug
